#!/usr/bin/env python3

from sys import argv, stdin

def parse_line(line, counts):
    counts[0] += 1
    if line != "\n":
        counts[1] += 1
    counts[2] += len(line)

def parse_file(name, counts):
    f = open(name)
    while (line := f.readline()) != "":
        parse_line(line, counts)

if __name__ == "__main__":
    counts = [0, 0, 0]
    if len(argv) > 1:
        for filename in argv[1:]:
            parse_file(filename, counts)
    else:
        for line in stdin:
            parse_line(line, counts)
    print("loc:\t%s\nsloc:\t%s\nbytes:\t%s" % tuple(counts))
